"""create material and material_list tables

Revision ID: bb3201f0eb86
Revises: 
Create Date: 2026-07-15 18:49:25.042999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3201f0eb86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metallic_yield', sa.Float(), nullable=False),
    sa.Column('fe_pct', sa.Float(), nullable=False),
    sa.Column('c_pct', sa.Float(), nullable=False),
    sa.Column('si_pct', sa.Float(), nullable=False),
    sa.Column('mn_pct', sa.Float(), nullable=False),
    sa.Column('p_pct', sa.Float(), nullable=False),
    sa.Column('s_pct', sa.Float(), nullable=False),
    sa.Column('cu_pct', sa.Float(), nullable=False),
    sa.Column('ni_pct', sa.Float(), nullable=False),
    sa.Column('sio2_pct', sa.Float(), nullable=False),
    sa.Column('al2o3_pct', sa.Float(), nullable=False),
    sa.Column('cao_pct', sa.Float(), nullable=False),
    sa.Column('mgo_pct', sa.Float(), nullable=False),
    sa.Column('feo_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_material_user_name')
    )
    op.create_index(op.f('ix_material_user_id'), 'material', ['user_id'], unique=False)
    op.create_table('material_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_material_list_user_name')
    )
    op.create_index(op.f('ix_material_list_user_id'), 'material_list', ['user_id'], unique=False)
    op.create_table('list_material',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['material_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'material_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_material')
    op.drop_index(op.f('ix_material_list_user_id'), table_name='material_list')
    op.drop_table('material_list')
    op.drop_index(op.f('ix_material_user_id'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
